Feature store list id (detail)
Prography-8th-team8/team8-BE pull request #17
Opened 2023-05-17 13:34 UTC by ympark99

## Feature/store-list-id
- 케이크샵 상세조회를 할 수 있어요.
- Naver search api를 연동했어요. (상세조회 반영)

### Comment
- 헥사고날에 맞게 작성하였는지 봐주시면 좋을 것 같습니다!
- StoreNaverSearchApiResponse와 정의가 겹치는데 분리하는게 좋을지, 통합하는게 좋을지 궁금합니다.
- @SuperBuilder를 사용하였는데 피드백 주시면 감사하겠습니다.

2023-05-17 13:35 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
> +@SuperBuilder
- StoreDetailResponse 클래스에서 StoreResponse를 상속하고 있으며, @Builder 애너테이션을 사용하고자 하는 경우에는 @SuperBuilder 애너테이션을 사용
- @SuperBuilder 애너테이션은 상속 관계에서 부모 클래스의 필드들도 빌더에 포함시키기 위해 사용

다른 방법이나 피드백 환영합니다!

2023-05-17 13:35 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +        int linkStartIndex = Objects.requireNonNull(responseJson).indexOf("\"link\":\"") + 8;
api 반환 값이 고정이라 고정적으로 반환했는데, JSON포맷으로 받아 처리할지 고민입니다.

2023-05-17 13:36 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +    public StoreNaverSearchApiResponse getNaverSearchApiResponse(String storeName){
out.web 에 정의하였는데 여기 정의하는게 헥사고날에 맞을지 궁금합니다.

2023-05-17 13:36 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/application/service/StoreService.java
> +        StoreNaverSearchApiResponse storeNaverSearchApiResponse = naverApiResult.getNaverSearchApiResponse(storeResponse.getName());
이 로직들은 service안에 구현해도 괜찮은지 궁금합니다.

2023-05-17 13:37 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
> +    String link; // 가게 URL
StoreNaverSearchApiResponse와 정의가 겹치는데, 통합할까요?
우선 사용성이 달라 분리하였습니다.

2023-05-21 11:50 UTC, govl6113 requested changes

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/in/web/StoreController.java
> +    @GetMapping("{id}")
@GetMapping("**/**{id}")가 좋을 것 같습니다!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +    public StoreNaverSearchApiResponse getNaverSearchApiResponse(String storeName){
naver api 와 관련된 out port와 out.external.adapter를 따로 두시면 될 것 같습니다! 이 어댑터는 out.external.adapter에 위치하면 되겠네요!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/application/service/StoreService.java
> +                                       storeNaverSearchApiResponse.getAddress());
storeNaverSearchApiResponse의 필드를 각각 넘기기 대신  storeNaverSearchApiResponse를 넘기면 좀 더 깔끔한 코드가 될 것 같아요! storeNaverSearchApiResponse의 모든 필드를 StoreDetailResponse에 넘기기 때문에 괜찮을 것 같아요.

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +public class NaverApiResult {
이름은 ~~ adapter가 좋을 것 같아요!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +        int linkStartIndex = Objects.requireNonNull(responseJson).indexOf("\"link\":\"") + 8;
넵. naver는 api 변동이 크니 json으로 처리하는게 좋을 것 같아요!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
> +    @QueryProjection
@QueryProjection는 querydsl을 사용할 때 select 부분에 필요한거라 여기에는 없어도 될 것 같아요!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
> +    String link; // 가게 URL
분리하죠!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
> +                .where(store.id.eq(storeId)) // where 조건 추가
where은 필터링 전 join을 하고, on은 필터링 후 join을 하는 것으로 알고 있습니다!
필터링 전 Join을 하게 되면 실제 필요한 join보다 훨씬 많이 될 것 같아서 여기서는 on을 사용하는게 적합할 것 같아요!

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/application/service/StoreService.java
> +        StoreNaverSearchApiResponse storeNaverSearchApiResponse = naverApiResult.getNaverSearchApiResponse(storeResponse.getName());
저는 맞다고 생각합니다! 대신 port를 사용해서 NaverSearchApiResponse를 가져와야 될 것 같아요~

2023-05-21 11:50 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/in/web/response/StoreDetailResponse.java
> +@SuperBuilder
@SuperBuilder 좋은 것 같아요!

2023-05-21 12:29 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +        int linkStartIndex = Objects.requireNonNull(responseJson).indexOf("\"link\":\"") + 8;
JSONObject 등 JSON 관련 로직에 애로사항이 있어 우선 머지 후 추후 리팩토링하는 방안으로 진행하겠습니다!

2023-05-21 12:37 UTC, ympark99 commented on src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
> +                .where(store.id.eq(storeId)) // where 조건 추가
on 절은 join 조건을 지정할 때 사용되며, where 절은 필터링 조건을 지정할 때 사용됩니다. on 절은 조인 시 관련 테이블 간의 조인 조건을 명시하는 데 사용되며, where 절은 쿼리 결과를 필터링하는 데 사용됩니다.
위의 코드에서는 store, storeAndTag, storeTag 테이블을 조인하고 storeId로 필터링하고자 합니다. 이 경우 where 절을 사용하여 필터링하는 것이 적합할 것 같습니다!
따라서, where 조건으로 진행하겠습니다!

2023-05-21 13:03 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/out/persistence/StorePersistenceAdapter.java
> +                .where(store.id.eq(storeId)) // where 조건 추가
http://ultteky.egloos.com/10411192 를 참고하면 두번째 예를 생각했던건데, 
제가 잘못 판단했네요.  where 좋습니다!

2023-05-21 13:03 UTC, govl6113 commented on src/main/java/prography/cakeke/server/store/adpter/out/web/NaverApiResult.java
> +        int linkStartIndex = Objects.requireNonNull(responseJson).indexOf("\"link\":\"") + 8;
넵!

2023-05-21 13:05 UTC, merged